# Generated by Django 5.2.17 on 2026-09-24 05:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=100, unique=True)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=120)),
                ('email', models.CharField(db_column='EmailAddress', max_length=255)),
                ('preferred_language', models.CharField(db_column='PreferredLanguage', default='en-US', max_length=10)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
                ('can_create_work_order', models.BooleanField(db_column='CanCreateWorkOrder', default=False)),
                ('can_fulfill_work_order', models.BooleanField(db_column='CanFulfillWorkOrder', default=False)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('pk', models.CompositePrimaryKey('employee', 'role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(db_column='EmployeeId', on_delete=django.db.models.deletion.CASCADE, to='workorders.employee')),
                ('role', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='workorders.role')),
            ],
            options={
                'db_table': 'EmployeeRoles',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', through='workorders.EmployeeRole', to='workorders.role'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, db_column='Number', max_length=7, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=300)),
                ('description', models.TextField(blank=True, db_column='Description', default='', max_length=4000)),
                ('instructions', models.TextField(blank=True, db_column='Instructions', default='', max_length=4000)),
                ('room_number', models.CharField(blank=True, db_column='RoomNumber', default='', max_length=900)),
                ('status', models.CharField(choices=[('DRT', 'Draft'), ('ASD', 'Assigned'), ('IPG', 'In Progress'), ('CMP', 'Complete'), ('CNL', 'Cancelled')], db_column='Status', default='DRT', max_length=3)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedDate', default=django.utils.timezone.now, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, db_column='AssignedDate', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='CompletedDate', null=True)),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='AssigneeId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='workorders.employee')),
                ('creator', models.ForeignKey(db_column='CreatorId', on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='workorders.employee')),
            ],
            options={
                'db_table': 'WorkOrder',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.UUIDField(db_column='Id', editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='FileName', max_length=500)),
                ('content_type', models.CharField(db_column='ContentType', max_length=200)),
                ('file_size', models.BigIntegerField(db_column='FileSize')),
                ('uploaded_date', models.DateTimeField(db_column='UploadedDate')),
                ('uploaded_by', models.ForeignKey(db_column='UploadedById', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='workorders.employee')),
                ('work_order', models.ForeignKey(db_column='WorkOrderId', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'db_table': 'WorkOrderAttachment',
                'ordering': ['uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=3)),
                ('to_status', models.CharField(max_length=3)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('work_order', models.ForeignKey(db_column='WorkOrderId', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workorders.workorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeerole',
            constraint=models.UniqueConstraint(fields=('employee', 'role'), name='employee_role_unique'),
        ),
    ]
