# Generated by Django 5.2.17 on 2026-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_role_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
