# Generated by Django 5.2.17 on 2026-09-24 02:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_alter_workorder_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='workorders.employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'ordering': ['uploaded_date'],
            },
        ),
    ]
