import {Config} from '@remotion/cli/config';

// Captured Playwright footage lives in video/footage/ (gitignored — regenerated by
// `npm run capture`), not the conventional public/ folder, so point Remotion's
// static-file resolution at it directly.
Config.setPublicDir('footage');

Config.setVideoImageFormat('jpeg');
Config.setOverwriteOutput(true);
Config.setCodec('h264');
Config.setCrf(28);
Config.setPixelFormat('yuv420p');
