BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[WorkOrder] Number column from NVARCHAR(6) to NVARCHAR(7)'
GO
ALTER TABLE [dbo].[WorkOrder] ALTER COLUMN [Number] NVARCHAR(7) NOT NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
PRINT 'The database update succeeded'
COMMIT TRANSACTION
GO
