BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Room]'
GO
CREATE TABLE [dbo].[Room]
(
	[Id]	UNIQUEIDENTIFIER	NOT NULL,
	[Name]	NVARCHAR(200)		NOT NULL,
	CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED ([Id])
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
PRINT 'The database update succeeded'
COMMIT TRANSACTION
GO
