import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { copyFileSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import path from 'node:path';

const port = Number(process.env.PORT || 3311);
const artifacts = path.resolve('artifacts');
mkdirSync(artifacts, { recursive: true });
for (const file of ['acceptance-video.webm', 'work-order-search-1365x900.png', 'work-order-search-1920x1080.png', 'work-order-manage-1365x900.png', 'work-order-manage-1920x1080.png', 'work-order-create-1365x900.png', 'work-order-create-1920x1080.png']) rmSync(path.join(artifacts, file), { force: true });
const database = path.resolve('acceptance.db');
rmSync(database, { force: true });
rmSync(`${database}-journal`, { force: true });
const server = spawn(process.execPath, ['dist/main.js'], { env: { ...process.env, PORT: String(port), DATABASE_URL: `file:${database}` }, stdio: 'inherit' });
let browser;
try {
  let ready = false;
  for (let i=0; i<60; i++) { try { if ((await fetch(`http://127.0.0.1:${port}/api/health`)).ok) { ready=true; break; } } catch {} await delay(250); }
  if (!ready) throw new Error('Prototype server did not become ready');
  browser = await chromium.launch({ headless: process.env.HEADFUL !== 'true' });
  const context = await browser.newContext({ recordVideo: { dir: artifacts, size: { width: 1280, height: 720 } } });
  const page = await context.newPage();
  const recording = page.video();
  await page.goto(`http://127.0.0.1:${port}`);
  await page.getByText('Service: ok').waitFor();
  await page.locator('#employee-select option[value="hsimpson"]').waitFor({ state: 'attached' });
  await page.getByTestId('login-user').selectOption('hsimpson');
  await page.getByTestId('login').click();
  await page.getByText('Welcome hsimpson!').waitFor();
  await page.locator('#search-form').waitFor({ state: 'visible' });
  const acceptanceTitle = 'Acceptance parity sample work order';
  await page.getByRole('link', { name: 'New Work Order' }).click();
  await page.waitForURL('**/workorder/manage');
  await page.getByTestId('title').fill(acceptanceTitle);
  const dateParts = new Intl.DateTimeFormat('en-US', { timeZone: 'America/Chicago', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date());
  const chicagoToday = `${dateParts.find(part => part.type === 'year').value}-${dateParts.find(part => part.type === 'month').value}-${dateParts.find(part => part.type === 'day').value}`;
  await page.getByTestId('description').fill('Browser acceptance flow');
  await page.getByTestId('instructions').fill('Use the side entrance');
  await page.getByTestId('room').fill('QA-7');
  await page.getByTestId('due-date').fill(chicagoToday);
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.screenshot({ path: path.join(artifacts, 'work-order-create-1365x900.png') });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: path.join(artifacts, 'work-order-create-1920x1080.png') });
  await page.getByTestId('save-draft').click();
  await page.getByText('Draft saved').waitFor();
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.locator('#search-route .page-title').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(artifacts, 'work-order-search-1365x900.png') });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: path.join(artifacts, 'work-order-search-1920x1080.png') });
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.locator('#orders tbody tr').filter({ hasText: acceptanceTitle }).getByRole('link').click();
  await page.waitForURL('**/workorder/manage/*');
  const newOrder = page.locator('#manage-content article').filter({ hasText: acceptanceTitle });
  await newOrder.waitFor();
  await page.screenshot({ path: path.join(artifacts, 'work-order-manage-1365x900.png') });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: path.join(artifacts, 'work-order-manage-1920x1080.png') });
  await newOrder.getByTestId('attachment-file-name').fill('damage-photo.jpg');
  await newOrder.getByTestId('attachment-content-type').fill('image/jpeg');
  await newOrder.getByTestId('attachment-file-size').fill('2048');
  await newOrder.getByTestId('add-attachment').click();
  await page.getByText('Attachment metadata added').waitFor();
  await page.getByTestId('attachment-row').getByText('damage-photo.jpg').waitFor();
  await page.getByTestId('attachment-row').getByText('Homer Simpson').waitFor();
  await page.getByTestId('due-date-value').getByText('Due Today').waitFor();
  await newOrder.getByRole('button', { name: 'Assign' }).click();
  await page.getByText('Work order assigned').waitFor();
  const assignedCard = page.locator('#manage-content article').filter({ hasText: acceptanceTitle });
  await assignedCard.getByRole('button', { name: 'Shelve' }).waitFor({ state: 'detached' });
  await assignedCard.getByRole('link', { name: /Back to Search/ }).click();
  await page.waitForURL('**/workorder/search');
  await page.getByTestId('search-assignee').selectOption('demo.tech');
  await page.getByTestId('search').click();
  const assignedResult = page.locator('#orders tbody tr').filter({ hasText: acceptanceTitle });
  await assignedResult.getByText(/Alex Technician/i).waitFor();
  await assignedResult.getByText('ASSIGNED', { exact: true }).waitFor();
  await page.locator('#orders tbody tr').filter({ hasText: acceptanceTitle }).getByRole('link').click();
  const workerOrder = page.locator('#manage-content article').filter({ hasText: acceptanceTitle });
  await workerOrder.waitFor();
  await page.getByTestId('logout').click();
  await page.getByTestId('login-user').selectOption('demo.tech');
  await page.getByTestId('login').click();
  await page.getByText('Welcome demo.tech!').waitFor();
  await workerOrder.getByRole('button', { name: 'Begin' }).click();
  await page.getByText('Work order in progress').waitFor();
  await workerOrder.getByRole('button', { name: 'Complete' }).click();
  await page.getByText('Work order complete').waitFor();
  await page.getByText('Complete', { exact: true }).last().waitFor();
  await workerOrder.getByRole('link', { name: /Back to Search/ }).click();
  await page.waitForURL('**/workorder/search');
  await page.getByTestId('search-status').selectOption('Complete');
  await page.getByTestId('search').click();
  await page.locator('#orders tbody tr').filter({ hasText: acceptanceTitle }).getByRole('link').click();
  const completedCard = page.locator('#manage-content article').filter({ hasText: acceptanceTitle });
  await completedCard.waitFor();
  await completedCard.getByRole('button', { name: 'History' }).click();
  await completedCard.getByTestId('event-history').getByText('Created').waitFor();
  await completedCard.getByTestId('event-history').getByText('Complete').waitFor();
  await page.getByTestId('logout').click();
  await page.getByTestId('login').waitFor();
  console.log('Acceptance passed: demo login → create → assign → assignee login → complete → logout');
  await context.close();
  if (!recording) throw new Error('Playwright did not create a video recorder for the acceptance page');
  const recordingPath = await recording.path();
  if (!existsSync(recordingPath)) throw new Error(`Playwright recording is missing: ${recordingPath}`);
  copyFileSync(recordingPath, path.join(artifacts, 'acceptance-video.webm'));
  const remotionPublic = path.resolve('remotion/public');
  mkdirSync(remotionPublic, { recursive: true });
  copyFileSync(recordingPath, path.join(remotionPublic, 'acceptance-video.webm'));
  console.log(`Recorded Playwright acceptance video: ${recordingPath}`);
} finally {
  await browser?.close();
  server.kill('SIGTERM');
}
