@startuml inprogresstocompletecommand-sequence-c4sequence
!include <C4/C4_Sequence>

UpdateElementStyle("system", $bgColor=#1a67be,$fontColor=#FFFFFF,$borderColor=#175eaa,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="2")
UpdateElementStyle("external_system", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="1")
UpdateElementStyle("person", $bgColor=#0d437b,$fontColor=#FFFFFF,$borderColor=#0d437b,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="2")
UpdateElementStyle("component", $bgColor=#85bbf0,$fontColor=#000000,$borderColor=#78a8d9,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="2")
UpdateElementStyle("external_component", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="1")
UpdateElementStyle("container", $bgColor=#438dd4,$fontColor=#FFFFFF,$borderColor=#3e82c5,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="2")
UpdateElementStyle("external_container", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness="1")
UpdateBoundaryStyle($elementName=system,$fontColor=#000000,$bgColor=#FFFFFF,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=container,$fontColor=#000000,$bgColor=#FFFFFF,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=enterprise,$fontColor=#000000,$bgColor=#FFFFFF,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
SHOW_PERSON_PORTRAIT()

title InProgressToCompleteCommand Sequence

Person(user, "User", "")
Component(api, "SingleApiController", "UI.Server", "API endpoint")
Component(bus, "Bus : IBus", "UI.Server", "Message bus")
Component(mediator, "IMediator", "MediatR", "")

Container_Boundary(cmdBound, "Command Pipeline")
    Component(cmd, "InProgressToCompleteCommand", "Command", "")
    Component(cmdHandler, "StateCommandHandler", "Handler", "")
    Component(order, "WorkOrder", "Domain", "")
Boundary_End()

ContainerDb(db, "DataContext / SQL Server", "Database:EF Core", "")

Rel(user, api, "User input")
Rel(api, bus, "Send(InProgressToCompleteCommand)")
Rel(bus, mediator, "Send(InProgressToCompleteCommand)")
Rel(mediator, cmdHandler, "Handle(StateCommandBase)")
Rel(cmdHandler, cmd, "Execute(StateCommandContext)")
Rel(cmd, order, "CompletedDate = CurrentDateTime")
Rel(cmd, order, "ChangeStatus(CurrentUser, date, Complete)")
Rel(cmdHandler, db, "SaveChangesAsync()")
Rel(cmdHandler, mediator, "StateCommandResult", "Complete")
@enduml
