/** Generated by scripts/generate-room-narration.cjs — do not edit by hand. */
export const AUDIO_HEAD_FRAMES = 18;
export const AUDIO_TAIL_FRAMES = 36;

export const NARRATION_SCENE_FRAMES = {
  intro: 315,
  before: 322,
  after: 330,
  reject: 335,
} as const;
