trigger:
  - "*"

variables:
  major: 1
  minor: 3
name: $(major).$(minor).$(Rev:r)

stages:
  - stage: "Integration_Build"
    displayName: "Build Application"

    jobs:
      - job: "Build"
        displayName: "Build on Windows"
        pool:
          vmImage: "windows-latest"
        steps:
          # Dependencies
          - task: UseDotNet@2
            displayName: "Install SDK 10.0.100"
            inputs:
              packageType: "sdk"
              version: "10.0.100"
              includePreviewVersions: true
          - task: UseDotNet@2
            displayName: "Install Runtime 6.0.0"
            inputs:
              packageType: "runtime"
              version: "6.0.0"
          # Manual .NET 10 SDK Installation (fallback)
          - task: PowerShell@2
            displayName: "Install .NET 10 SDK Manually"
            inputs:
              pwsh: true
              targetType: "inline"
              script: |
                Write-Host "Checking current SDK..."
                dotnet --list-sdks
                dotnet --version
                
                # Check if .NET 10 SDK is already available
                $sdks = dotnet --list-sdks
                if ($sdks -match "10\.0\.") {
                  Write-Host "? .NET 10 SDK is already installed"
                  exit 0
                }
                
                # Download and install .NET 10 SDK using official installer script
                Write-Host "Downloading .NET 10 SDK installer script..."
                try {
                  Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$env:TEMP\dotnet-install.ps1"
                  Write-Host "Installing .NET 10 SDK..."
                  & "$env:TEMP\dotnet-install.ps1" -Channel 10.0 -Quality preview -InstallDir "$env:ProgramFiles\dotnet" -NoPath
                  
                  Write-Host "? SDK installation completed"
                  Write-Host "Available SDKs:"
                  dotnet --list-sdks
                  dotnet --version
                } catch {
                  Write-Warning "? Could not install SDK: $_"
                  Write-Host "Attempting to continue with existing SDKs..."
                  dotnet --list-sdks
                }
          # Set environment variables
          - task: PowerShell@2
            displayName: "Set Version Environment Variable"
            inputs:
              pwsh: true
              targetType: "inline"
              script: |
                [System.Environment]::SetEnvironmentVariable('Version','$(Build.BuildNumber)')
                echo "Build Version: $env:Version"
          - task: PowerShell@2
            displayName: "Run CIBuild"
            inputs:
              pwsh: true
              targetType: filePath
              filePath: ./build.ps1
              arguments: ";Invoke-CIBuild"
          - task: PublishTestResults@2
            displayName: "Publish Test Results ./build/test/*.trx"
            inputs:
              testResultsFormat: VSTest
              testResultsFiles: "build/test/**/*.trx"
              mergeTestResults: true
              testRunTitle: "CI Tests"
            continueOnError: true
            condition: succeededOrFailed()
          - task: PublishCodeCoverageResults@2
            displayName: "Publish code coverage UnitTests"
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/build/test/**/In/**/coverage.cobertura.xml"
          - task: PowerShell@2
            displayName: "Package Nugets"
            inputs:
              pwsh: true
              targetType: filePath
              filePath: ./build.ps1
              arguments: ";Package-Everything"          
          - task: DotNetCoreCLI@2
            displayName: "Push NuGet packages."
            inputs:
              command: "push"
              packagesToPush: "$(System.DefaultWorkingDirectory)/build/*.nupkg"
              nuGetFeedType: "internal"
              publishVstsFeed: "$(AzureFeedName)"
      - job: "DockerBuildandPush"
        pool:
          vmImage: "ubuntu-latest"
        dependsOn: Build

        steps:
          - task: DownloadPackage@1
            displayName: "Download UI Package"
            inputs:
              packageType: "nuget"
              feed: "$(AzureFeedName)"
              view: "Local"
              definition: "ChurchBulletin.UI"
              version: "$(Build.BuildNumber)"
              downloadPath: "$(System.DefaultWorkingDirectory)/built"
              extract: true

          - task: Docker@2
            inputs:
              containerRegistry: "$(AzureContainerRegistry)"
              repository: "ChurchBulletin.UI"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(Build.BuildNumber)

  # Deploying to TDD
  - stage: "TDD"
    displayName: "TDD"
    jobs:
      - deployment: "DeployToTDD"
        pool:
          vmImage: "windows-latest"
        environment: "TDD"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Baseline database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServer)" -DatabaseName "ChurchBulletin" -DatabaseAction "baseline" -DatabaseUser "tdd" -DatabasePassword "$(DatabasePassword)"                    
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServer)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "tdd" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-tdd --image $(containerImage)

                - task: DownloadPackage@1
                  displayName: "Download Acceptance Test Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.AcceptanceTests"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)/tests"
                    extract: true
                - task: DownloadPackage@1
                  displayName: "Download ChurchBulletin.Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)/database"
                    extract: true

                - task: PowerShell@2
                  displayName: "Run ChurchBulletin.Database migration"
                  inputs:
                    pwsh: true
                    targetType: "inline"
                    script: |
                      $databaseDll = Get-ChildItem -Path "$(System.DefaultWorkingDirectory)/database" -Filter "ClearMeasure.Bootcamp.Database.dll" -Recurse | Select-Object -First 1
                      if ($databaseDll) {
                        dotnet $databaseDll.FullName "$(DatabaseAction)" "$(DatabaseServer)" "ChurchBulletin" "$(System.DefaultWorkingDirectory)/database/scripts" "tdd" "$(DatabasePassword)"
                      } else {
                        Write-Error "ClearMeasure.Bootcamp.Database.dll not found in downloaded package"
                        exit 1
                      }

                - task: PowerShell@2
                  displayName: "Install Playwright"
                  inputs:
                    pwsh: true
                    targetType: "inline"
                    script: |
                      pwsh ./tests/playwright.ps1 install --with-deps

                - task: VSTest@2
                  continueOnError: true
                  displayName: "VsTest - AcceptanceTests"
                  inputs:
                    testSelector: "testAssemblies"
                    testAssemblyVer2: |
                      **\*AcceptanceTests.dll
                      !**\*TestAdapter.dll
                      !**\obj\**
                      searchFolder: '$(System.DefaultWorkingDirectory)/tests'
                    uiTests: true
                    codeCoverageEnabled: true
                    testRunTitle: "Acceptance Tests"
                    diagnosticsEnabled: True
                    rerunFailedTestCasesMaxLimit: 3
                    rerunFailedTests: true
                    rerunMaxAttempts: 2
                    rerunType: basedOnTestFailureCount

  # Deploying to UAT
  - stage: "UAT"
    displayName: "UAT"
    condition: eq(variables['Build.Reason'], 'Manual')
    jobs:
      - deployment: "DeployToUAT"
        pool:
          vmImage: "windows-latest"
        environment: "UAT"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServerUAT)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "uat" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-uat --image $(containerImage)

  # Deploying to PROD
  - stage: "PROD"
    displayName: "PROD"
    jobs:
      - deployment: "DeployToPROD"
        pool:
          vmImage: "windows-latest"
        environment: "PROD"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServerPROD)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "prod" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-prod --image $(containerImage)
