trigger:
  - "*"

variables:
  major: 1
  minor: 3
name: $(major).$(minor).$(Rev:r)

stages:
  - stage: "Integration_Build"
    displayName: "Build Application"

    jobs:
      - job: "Build"
        displayName: "Build on Windows"
        pool:
          vmImage: "windows-latest"
        steps:
          # Dependencies
          - task: UseDotNet@2
            displayName: "Install SDK 9.0.302"
            inputs:
              packageType: "sdk"
              version: "9.0.302"
          - task: UseDotNet@2
            displayName: "Install Runtime 6.0.0"
            inputs:
              packageType: "runtime"
              version: "6.0.0"
          # Start SQL Server LocalDB
          - task: PowerShell@2
            displayName: "Start and Verify SQL Server LocalDB (Windows only)"
            condition: eq(variables['Agent.OS'], 'Windows_NT')
            inputs:
              pwsh: true
              targetType: "inline"
              script: |
                Write-Host "Starting SQL Server LocalDB..."
                sqllocaldb create MSSQLLocalDB -s
                sqllocaldb start MSSQLLocalDB
                sqllocaldb info MSSQLLocalDB
                
                Write-Host "Waiting for LocalDB to be ready..."
                $maxAttempts = 30
                $attempt = 0
                $ready = $false
                
                while (-not $ready -and $attempt -lt $maxAttempts) {
                    $attempt++
                    try {
                        $conn = New-Object System.Data.SqlClient.SqlConnection("Server=(LocalDb)\MSSQLLocalDB;Integrated Security=true;Connection Timeout=5")
                        $conn.Open()
                        $conn.Close()
                        $ready = $true
                        Write-Host "LocalDB is ready after $attempt attempts"
                    }
                    catch {
                        Write-Host "Attempt $attempt : $_"
                        Start-Sleep -Seconds 2
                    }
                }
                
                if (-not $ready) {
                    throw "LocalDB failed to start after $maxAttempts attempts"
                }
          # Set environment variables
          - task: PowerShell@2
            displayName: "Set Version Environment Variable"
            inputs:
              pwsh: true
              targetType: "inline"
              script: |
                [System.Environment]::SetEnvironmentVariable('Version','$(Build.BuildNumber)')
                echo "Build Version: $env:Version"
          - task: PowerShell@2
            displayName: "Run the Powershell build script"
            inputs:
              pwsh: true
              targetType: filePath
              filePath: ./build.ps1
              arguments: ";Invoke-CIBuild"
          - task: PublishTestResults@2
            displayName: "Publish Test Results ./build/test/*.trx"
            inputs:
              testResultsFormat: VSTest
              testResultsFiles: "build/test/**/*.trx"
              mergeTestResults: true
              testRunTitle: "CI Tests"
            continueOnError: true
            condition: succeededOrFailed()
          - task: PublishCodeCoverageResults@2
            displayName: "Publish code coverage UnitTests"
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/build/test/**/In/**/coverage.cobertura.xml"
          - task: DotNetCoreCLI@2
            displayName: "Push NuGet packages."
            inputs:
              command: "push"
              packagesToPush: "$(System.DefaultWorkingDirectory)/build/*.nupkg"
              nuGetFeedType: "internal"
              publishVstsFeed: "$(AzureFeedName)"
      - job: "DockerBuildandPush"
        pool:
          vmImage: "ubuntu-latest"
        dependsOn: Build

        steps:
          - task: DownloadPackage@1
            displayName: "Download UI Package"
            inputs:
              packageType: "nuget"
              feed: "$(AzureFeedName)"
              view: "Local"
              definition: "ChurchBulletin.UI"
              version: "$(Build.BuildNumber)"
              downloadPath: "$(System.DefaultWorkingDirectory)/built"
              extract: true

          - task: Docker@2
            inputs:
              containerRegistry: "$(AzureContainerRegistry)"
              repository: "ChurchBulletin.UI"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(Build.BuildNumber)
    #Azure junk db passwords - hsimpson123! - user is the name of the environment

  # Deploying to TDD
  - stage: "TDD"
    displayName: "TDD"
    jobs:
      - deployment: "DeployToTDD"
        pool:
          vmImage: "windows-latest"
        environment: "TDD"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServer)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "tdd" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-tdd --image $(containerImage)

                - task: DownloadPackage@1
                  displayName: "Download Acceptance Test Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.AcceptanceTests"
                    version: "$(Build.Buildnumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)/tests"
                    extract: true
                - task: DownloadPackage@1
                  displayName: "Download ChurchBulletin.Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.Buildnumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)/database"
                    extract: true

                - task: PowerShell@2
                  displayName: "Install Playwright"
                  inputs:
                    pwsh: true
                    targetType: "inline"
                    script: |
                      pwsh ./tests/playwright.ps1 install --with-deps

                - task: VSTest@2
                  continueOnError: true
                  displayName: "VsTest - AcceptanceTests"
                  inputs:
                    testSelector: "testAssemblies"
                    testAssemblyVer2: |
                      **\*AcceptanceTests.dll
                      !**\*TestAdapter.dll
                      !**\obj\**
                    searchFolder: '$(System.DefaultWorkingDirectory)/tests'
                    runSettingsFile: '$(System.DefaultWorkingDirectory)/tests/AcceptanceTests.runsettings'
                    uiTests: true
                    codeCoverageEnabled: true
                    testRunTitle: "Acceptance Tests"
                    diagnosticsEnabled: True
                    rerunFailedTestCasesMaxLimit: 3
                    rerunFailedTests: true
                    rerunMaxAttempts: 2
                    rerunType: basedOnTestFailureCount

  # Deploying to UAT
  - stage: "UAT"
    displayName: "UAT"
    condition: eq(variables['Build.Reason'], 'Manual')
    jobs:
      - deployment: "DeployToUAT"
        pool:
          vmImage: "windows-latest"
        environment: "UAT"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.Build.Number)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServerUAT)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "uat" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-uat --image $(containerImage)

  # Deploying to PROD
  - stage: "PROD"
    displayName: "PROD"
    jobs:
      - deployment: "DeployToPROD"
        pool:
          vmImage: "windows-latest"
        environment: "PROD"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: "Download Database Package"
                  inputs:
                    packageType: "nuget"
                    feed: "$(AzureFeedName)"
                    view: "Local"
                    definition: "ChurchBulletin.Database"
                    version: "$(Build.BuildNumber)"
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                    extract: true
                - task: PowerShell@2
                  displayName: "Create database schema"
                  inputs:
                    pwsh: true
                    targetType: filePath
                    filePath: ./scripts/UpdateAzurePipelineSql.ps1
                    arguments: -DatabaseServer "$(DatabaseServerPROD)" -DatabaseName "ChurchBulletin" -DatabaseAction "$(DatabaseAction)" -DatabaseUser "prod" -DatabasePassword "$(DatabasePassword)"

                - task: AzureCLI@2
                  displayName: "Add revision to container app"
                  inputs:
                    azureSubscription: "$(AzureSubscription)"
                    scriptType: "ps"
                    scriptLocation: "inlineScript"
                    inlineScript: az containerapp update --name $(containerAppName) --resource-group bootcamp-prod --image $(containerImage)
