from catalog_data import GUILDS
rows=[r for g in GUILDS for r in g['rows']]
FAM={
'CTRL':'event-router timer-scheduler work-claim-lock lane-dispatcher lane-stall-watchdog agent-budget-governor model-router human-escalation-router human-decision-recorder audit-trail-keeper agent-registry-keeper kill-switch-guardian wip-limit-enforcer board-column-mover work-item-linker dependency-graph-resolver merge-readiness-checker pr-merger protected-path-guard change-risk-scorer migration-numbering-guard version-bumper deploy-freeze-enforcer environment-promotion-tracker docs-only-fast-path definition-of-ready-checker definition-of-done-checker item-closure-verifier policy-keeper human-gate-queue-balancer needs-info-follower support-sla-watcher release-candidate-cutter artifact-publisher',
'PROBE':'health-check-monitor dependency-health-watcher certificate-expiry-watcher quota-limit-watcher drift-detector schema-drift-detector backup-verifier db-capacity-watcher cloud-cost-reporter flow-metrics-reporter dora-metrics-collector error-budget-tracker log-anomaly-detector metric-anomaly-detector cost-anomaly-detector fitness-function-runner complexity-trend-watcher local-build-time-tracker cold-start-analyzer bundle-size-watcher eol-runtime-watcher build-reproducibility-checker finops-ai-spend-reporter tagging-compliance-enforcer dev-environment-validator runner-fleet-manager ephemeral-env-reaper idle-resource-reaper ci-pipeline-watcher test-report-publisher flaky-test-detector release-scope-tracker environment-promotion-tracker data-pipeline-monitor unit-cost-calculator budget-forecaster',
'SCAN':'sast-scanner secret-scanner sca-scanner dast-scanner container-image-scanner iac-security-scanner license-compliance-checker typosquat-malware-checker sbom-generator action-pinning-auditor lockfile-drift-auditor abandoned-package-detector a11y-static-checker color-contrast-checker i18n-string-extractor pseudo-localization-runner link-checker crap-score-gate static-analysis-triager authz-matrix-auditor network-exposure-auditor cookie-consent-auditor contributor-license-checker agent-permission-auditor duplication-detector seo-auditor data-quality-checker supply-chain-attestation third-party-notice-writer api-breaking-change-detector architecture-rule-enforcer pii-data-classifier mutation-tester coverage-gap-analyzer',
'READ':'owner-request-intake work-item-classifier duplicate-detector intake-channel-bridge support-ticket-triager feature-request-analyzer feature-feedback-router sentiment-analyzer market-signal-miner competitive-scanner customer-interview-synthesizer survey-analyzer bug-report-quality-coach security-report-intake question-answerer research-repository-keeper regulatory-change-watcher error-tracker-triager customer-log-investigator',
'LENS':'code-review-orchestrator correctness-reviewer style-conventions-reviewer test-adequacy-reviewer simplification-reviewer security-review-agent ef-query-reviewer ui-consistency-auditor visual-regression-reviewer migration-reviewer cost-impact-reviewer observability-gap-finder doc-drift-checker pr-size-guard bot-finding-triager design-review-board scalability-reviewer rate-limit-validator new-dependency-gate conflict-arbiter',
'SPEC':'request-clarifier problem-statement-writer hypothesis-framer product-requirements-writer acceptance-criteria-writer technical-design-author adr-writer api-contract-designer data-model-designer threat-modeler nfr-specifier integration-designer security-requirements-writer ux-flow-designer ui-component-designer ux-copy-writer ux-test-plan-writer test-design-author tracking-plan-author experiment-designer survey-designer slo-definer alert-rule-author refactoring-planner infra-change-planner spike-runner prototype-builder design-system-curator metric-definition-keeper persona-maintainer',
'BUILD':'feature-implementer backend-implementer frontend-implementer fix-implementer api-endpoint-implementer migration-author refactoring-implementer mechanical-cleanup-fixer feature-flag-wirer config-change-implementer dead-code-remover sdk-client-generator deprecation-implementer data-pipeline-implementer llm-feature-implementer vuln-fixer stale-flag-remover dependency-update-proposer base-image-updater scaffolding-generator iac-implementer index-advisor analytics-schema-maintainer kpi-dashboard-builder dashboard-maintainer translation-generator code-comment-documenter api-sandbox-maintainer session-start-hook-maintainer golden-path-maintainer pipeline-as-code-maintainer ci-duration-optimizer ci-infra-fixer container-runtime-tuner permission-prompt-reducer inner-loop-optimizer build-warning-reducer',
'REPAIR':'review-feedback-applier ci-failure-fixer merge-conflict-resolver branch-updater flaky-test-quarantiner flaky-test-fixer',
'TEST':'unit-test-author integration-test-author acceptance-test-author ui-component-test-author contract-test-author test-data-generator security-test-author load-test-author synthetic-monitor-author bug-reproducer',
'VERIFY':'functional-test-runner exploratory-tester smoke-test-runner cross-browser-runner bug-verification-agent llm-eval-runner chaos-experiment-runner load-test-runner perf-regression-analyzer benchmark-runner profiler-agent query-performance-analyzer frontend-perf-auditor stress-breakpoint-tester soak-tester a11y-runtime-auditor keyboard-nav-tester screen-reader-tester locale-format-tester ux-walkthrough-recorder usability-heuristic-evaluator instrumentation-verifier release-verifier dr-drill-runner regression-suite-curator test-env-provisioner deadlock-analyzer incident-diagnostician',
'OPS':'deployment-orchestrator migration-deploy-runner progressive-rollout-controller rollback-executor hotfix-release-runner feature-flag-manager environment-provisioner dns-domain-manager os-patch-manager secrets-store-maintainer secret-rotation-runner secret-leak-responder db-maintenance-runner data-retention-enforcer db-restore-to-lower-env pii-data-masker data-migration-runner rightsizing-advisor runbook-executor waf-rule-tuner data-subject-request-handler',
'INCIDENT':'incident-declarer incident-commander on-call-pager status-page-updater postmortem-writer action-item-filer customer-incident-notifier hotfix-intake',
'PLAN':'backlog-prioritizer backlog-groomer estimator story-splitter sprint-planner epic-decomposer opportunity-scorer roadmap-planner release-planner capacity-planner capacity-allocator portfolio-balancer cross-repo-dependency-coordinator dependency-upgrade-planner commitment-planner blocked-item-unblocker stale-issue-gardener bug-severity-assessor vuln-triager',
'REPORT':'okr-progress-tracker weekly-metrics-digest stakeholder-status-reporter engineering-health-reporter security-posture-reporter quarterly-business-review-writer raid-log-keeper milestone-risk-assessor funnel-analyzer cohort-retention-analyzer customer-usage-reporter ad-hoc-question-answerer customer-health-reporter churn-risk-detector internal-digest-writer experiment-readout feature-adoption-reviewer user-journey-analytics-reviewer telemetry-cost-optimizer saas-license-auditor compliance-evidence-collector control-gap-assessor change-approval-recorder codebase-cartographer tech-radar-curator',
'MINE':'signal-aggregator backlog-generator-from-signals recurring-failure-miner revert-analyzer escaped-defect-analyzer rework-detector agent-friction-miner goal-drift-detector quality-trend-sentinel tech-debt-registrar toil-tracker alert-noise-reducer doc-gap-detector resilience-improvement-planner retrospective-facilitator process-improvement-implementer',
'WRITE':'pr-description-writer release-notes-writer changelog-generator api-reference-generator user-guide-writer readme-maintainer runbook-librarian glossary-maintainer tutorial-writer diagram-renderer docs-site-publisher onboarding-guide-maintainer kb-article-writer support-ticket-resolver support-macro-maintainer faq-updater close-the-loop-notifier customer-onboarding-assistant release-comms-writer deprecation-notice-writer changelog-page-publisher social-post-drafter demo-script-writer sales-enablement-writer website-content-updater architecture-diagram-updater runbook-author security-guidance-writer security-advisory-publisher',
'GATE':'repo-onboarder product-vision-keeper okr-drafter pricing-packaging-analyst business-case-writer sunset-planner ux-acceptance-gate perf-budget-keeper access-review-runner pen-test-coordinator prod-deploy-gate human-review-requester agent-proposal-gate idea-incubator a11y-conformance-reporter translation-reviewer privacy-impact-assessor policy-text-watcher legal-review-requester export-control-checker ai-system-register-keeper code-ownership-mapper',
'META':'agent-output-evaluator agent-eval-regression-runner agent-prompt-tuner agent-performance-reviewer skill-library-curator human-override-learner ai-worker-mix-manager owner-friction-surveyor',
}
m={}
for f,s in FAM.items():
    for n in s.split():
        if n in m and m[n]!=f: pass
        m.setdefault(n,f)
names={r['name'] for r in rows}
print('unassigned',sorted(names-set(m)))
print('bogus',sorted(set(m)-names))
import collections
c=collections.Counter(m[n] for n in names if n in m); print(c, sum(c.values()))
